// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv37L6cLhfo7IMVJErYl-1dqZGFFWmPh0',
    appId: '1:337577804464:web:ca73560b6327a786adf175',
    messagingSenderId: '337577804464',
    projectId: 'e-wallet-e9153',
    authDomain: 'e-wallet-e9153.firebaseapp.com',
    storageBucket: 'e-wallet-e9153.appspot.com',
    measurementId: 'G-T85R9XZ0G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV8GErmte-WJw-0cIvb0YhT9o9XQb5--o',
    appId: '1:337577804464:android:88bf198512b3ae43adf175',
    messagingSenderId: '337577804464',
    projectId: 'e-wallet-e9153',
    storageBucket: 'e-wallet-e9153.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIxemM5qnD1p6bRjqKJPtWoLeZBppTIlI',
    appId: '1:337577804464:ios:8dc2b58d50f7beffadf175',
    messagingSenderId: '337577804464',
    projectId: 'e-wallet-e9153',
    storageBucket: 'e-wallet-e9153.appspot.com',
    iosClientId:
        '337577804464-vlnparb6us1398o2p21teajephmv5gek.apps.googleusercontent.com',
    iosBundleId: 'com.example.paml20190140086Ewallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIxemM5qnD1p6bRjqKJPtWoLeZBppTIlI',
    appId: '1:337577804464:ios:8dc2b58d50f7beffadf175',
    messagingSenderId: '337577804464',
    projectId: 'e-wallet-e9153',
    storageBucket: 'e-wallet-e9153.appspot.com',
    iosClientId:
        '337577804464-vlnparb6us1398o2p21teajephmv5gek.apps.googleusercontent.com',
    iosBundleId: 'com.example.paml20190140086Ewallet',
  );
}
