import 'package:flutter/material.dart';
import 'package:expensetracker/presentation/pages/auth/login_page.dart';
import 'package:expensetracker/presentation/pages/home_page.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Future.delayed(const Duration(seconds: 1));
  FlutterNativeSplash.remove();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  SharedPreferences.getInstance().then((instance) {
    String uid = '';
    if (instance.containsKey('uid')) {
      uid = instance.getString('uid') ?? '';
    }
    runApp(MyApp(hasSession: uid.isNotEmpty));
  });
}

//Explanation of what the query code is for
//What will be generated by this query when run
class MyApp extends StatelessWidget {
  const MyApp({super.key, required this.hasSession});

  final bool hasSession;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Expense Tracker',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: hasSession ? const HomePage() : const LoginPage(),
        debugShowCheckedModeBanner: false);
  }
}
